package com.github.itroadlabs.oas.apicross.core;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Enables ability to add custom attributes for models generated by the Core.
 * In general it is for custom attributes to use in source code templates.
 */
public abstract class HasCustomModelAttributes {
    private final Map<String, Object> modelAttributes = new LinkedHashMap<>();

    public void addCustomAttribute(String name, Object value) {
        this.modelAttributes.put(name, value);
    }

    public Map<String, Object> getCustomAttributes() {
        return Collections.unmodifiableMap(modelAttributes);
    }
}
